server:
  # 端口
  port: 8881
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/star_oj
    username: root
    password: root
    druid:
      test-on-borrow: true
      test-while-idle: true
      max-active: 8
      min-idle: 4
      validation-query: SELECT 1
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
#    password: root
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  # email 配置
  mail:
    host: smtp.163.com  # 163邮箱的smtp HAXKDYSCOCFZWCZL mM@+auvUVL-wv9W
    username: youEmile
    password: EmilePassword
    port: 25
    properties:
      mail:
        default-encoding: utf-8
        smtp:
          # 连接超时时间
          connectionTimeout: 5000
          # 发送超时时间
          timeout: 3000
          # 写入超时时间
          writeTimeout: 5000
          auth: true
          starttls:
            required: true
            enable: true


logging:
  level:
    root: info
    com.example.hospital.api.db.dao: warn
  pattern:
    console: "%d{yyyy/MM/dd HH:mm:ss}  %-5level  %msg%n"

